"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.usersApi = exports.userRolesApi = exports.translationsApi = exports.spacesApi = exports.settingsApi = exports.sectionsApi = exports.recycleBinApi = exports.pagesApi = exports.pageTreeApi = exports.modulesApi = exports.mediaApi = exports.mediaFolderApi = exports.mailTemplatesApi = exports.linksApi = exports.languagesApi = exports.intergrationsApi = exports.countriesApi = exports.applicationsApi = void 0;
var applications_js_1 = require("./applications.js");
Object.defineProperty(exports, "applicationsApi", { enumerable: true, get: function () { return applications_js_1.default; } });
var countries_js_1 = require("./countries.js");
Object.defineProperty(exports, "countriesApi", { enumerable: true, get: function () { return countries_js_1.default; } });
var integrations_js_1 = require("./integrations.js");
Object.defineProperty(exports, "intergrationsApi", { enumerable: true, get: function () { return integrations_js_1.default; } });
var languages_js_1 = require("./languages.js");
Object.defineProperty(exports, "languagesApi", { enumerable: true, get: function () { return languages_js_1.default; } });
var links_js_1 = require("./links.js");
Object.defineProperty(exports, "linksApi", { enumerable: true, get: function () { return links_js_1.default; } });
var mailTemplates_js_1 = require("./mailTemplates.js");
Object.defineProperty(exports, "mailTemplatesApi", { enumerable: true, get: function () { return mailTemplates_js_1.default; } });
var media_folder_js_1 = require("./media-folder.js");
Object.defineProperty(exports, "mediaFolderApi", { enumerable: true, get: function () { return media_folder_js_1.default; } });
var media_js_1 = require("./media.js");
Object.defineProperty(exports, "mediaApi", { enumerable: true, get: function () { return media_js_1.default; } });
var modules_js_1 = require("./modules.js");
Object.defineProperty(exports, "modulesApi", { enumerable: true, get: function () { return modules_js_1.default; } });
var page_tree_js_1 = require("./page-tree.js");
Object.defineProperty(exports, "pageTreeApi", { enumerable: true, get: function () { return page_tree_js_1.default; } });
var pages_js_1 = require("./pages.js");
Object.defineProperty(exports, "pagesApi", { enumerable: true, get: function () { return pages_js_1.default; } });
var recycle_bin_js_1 = require("./recycle-bin.js");
Object.defineProperty(exports, "recycleBinApi", { enumerable: true, get: function () { return recycle_bin_js_1.default; } });
var sections_js_1 = require("./sections.js");
Object.defineProperty(exports, "sectionsApi", { enumerable: true, get: function () { return sections_js_1.default; } });
var settings_js_1 = require("./settings.js");
Object.defineProperty(exports, "settingsApi", { enumerable: true, get: function () { return settings_js_1.default; } });
var spaces_js_1 = require("./spaces.js");
Object.defineProperty(exports, "spacesApi", { enumerable: true, get: function () { return spaces_js_1.default; } });
var translations_js_1 = require("./translations.js");
Object.defineProperty(exports, "translationsApi", { enumerable: true, get: function () { return translations_js_1.default; } });
var userRoles_js_1 = require("./userRoles.js");
Object.defineProperty(exports, "userRolesApi", { enumerable: true, get: function () { return userRoles_js_1.default; } });
var users_js_1 = require("./users.js");
Object.defineProperty(exports, "usersApi", { enumerable: true, get: function () { return users_js_1.default; } });
//# sourceMappingURL=index.js.map